### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'mpv'

### ISSUE THREAD

**Issue by timonvanhasselt** [OpenVoiceOS/ovos-audio-plugin-mpv#5]
I've tested `ovos-audio-plugin-mpv` (0.0.0a4) with `ovos-config` (0.0.13a24), but get this`MPV not found` error. 

2024-07-18 17:10:22.219 - audio - ovos_audio.audio:play:432 - ERROR - failed to play with <ovos_plugin_mpv.OVOSMPVService object at 0x7f531dff24d0>
Traceback (most recent call last):
  File "/home/ovos/.venvs/ovos/lib/python3.11/site-packages/ovos_audio/audio.py", line 429, in play
    self.current.play(repeat)
  File "/home/ovos/.venvs/ovos/lib/python3.11/site-packages/ovos_plugin_mpv/__init__.py", line 102, in play
    self.init_mpv()
  File "/home/ovos/.venvs/ovos/lib/python3.11/site-packages/ovos_plugin_mpv/__init__.py", line 27, in init_mpv
    self.mpv = MPV()
               ^^^^^
  File "/home/ovos/.venvs/ovos/lib/python3.11/site-packages/python_mpv_jsonipc.py", line 430, in __init__
    self.mpv_process = MPVProcess(ipc_socket, mpv_location, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venvs/ovos/lib/python3.11/site-packages/python_mpv_jsonipc.py", line 236, in __init__
    self.process = subprocess.Popen(args)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mpv'

**Comment by timonvanhasselt** [comment]
Or just read the[ Readme/ prerequisites](https://github.com/OpenVoiceOS/ovos-audio-plugin-mpv?tab=readme-ov-file#prerequisites) better @Timon 🙈

> Ensure you have the following installed on your system:
> 
> Python 3.6 or higher
> **MPV media player**
> Open Voice OS (OVOS) components

In my case: `sudo apt install mpv`
